services:
  - name: backend-service
    type: web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: DB_HOST
        value: postgres_container
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: ${DB_USER}
      - key: DB_PASSWORD
        value: ${DB_PASSWORD}
      - key: DB_NAME
        value: ${DB_NAME}
      - key: REDIS_HOST
        value: redis_container
      - key: REDIS_PORT
        value: 6379
      - key: JWT_SECRET
        value: ${JWT_SECRET}
